name: .NET Test with Coverage Report

on:
  push:
    paths:
    - 'TopologyCardRegister/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'TopologyCardRegister/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      working-directory: ./TopologyCardRegister
      run: dotnet restore
      
    - name: Build
      working-directory: ./TopologyCardRegister
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./TopologyCardRegister
      id: test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      working-directory: ./TopologyCardRegister/TopologyCardRegister.Tests/
      run: |
        reportgenerator "-reports:./TestResults/*/coverage.cobertura.xml" "-targetdir:coverage_report" "-reporttypes:Html;TextSummary"
        cat coverage_report/Summary.txt
      shell: pwsh

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./TopologyCardRegister/TopologyCardRegister.Tests/coverage_report/

    - name: Code Coverage Report
      uses: insightsengineering/coverage-action@v2
      with:
        # Path to the Cobertura XML report.
        path: ./TopologyCardRegister/TopologyCardRegister.Tests/TestResults/*/coverage.cobertura.xml
        # Minimum total coverage, if you want to the
        # workflow to enforce it as a standard.
        # This has no effect if the `fail` arg is set to `false`.
        threshold: 80
        # Fail the workflow if the minimum code coverage
        # reuqirements are not satisfied.
        fail: true
        # Publish the rendered output as a PR comment
        publish: true
        # Create a coverage diff report.
        diff: true
        # Branch to diff against.
        # Compare the current coverage to the coverage
        # determined on this branch.
        diff-branch: main
        # This is where the coverage reports for the
        # `diff-branch` are stored.
        # Branch is created if it doesn't already exist'.
        diff-storage: _xml_coverage_reports


